twig:
    file_name_pattern: '*.twig'
    strict_variables: false
    debug: false
    cache: false
    form_themes: 
        - 'bootstrap_4_layout.html.twig'

when@test:
    strict_variables: false
    debug: false
